version: '3'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4999:4999"
    environment:
      FLASK_ENV: production
    volumes:
      - ./app:/app
      - ./videos:/app/videos
  nginx:
    build:
      context: ./nginx
    ports:
      - "8092:80"
    depends_on:
      - flask-app
