version: '3'

services:
  flask-app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4999:4999"
    environment:
      FLASK_ENV: production
    volumes:
      - ./app:/app
      - ${VIDEOS_DIR:-./videos}:/app/videos
    command: sh -c 'pip install -U yt-dlp && python app.py'
  nginx:
    build:
      context: ./nginx
    ports:
      - "8092:80"
    depends_on:
      - flask-app
    volumes:
      - ./static:/static
      - ${VIDEOS_DIR:-./videos}:/videos
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf

